### ISSUE TITLE
Change Tracking

### ISSUE THREAD

**Issue by gav5** [jmennick/cornDog#3]
Each change to a record in the database must be tracked.

**Comment by gav5** [comment]
A gem I've seen used for this kind of thing is [paper_trail](https://github.com/airblade/paper_trail).

I know this doesn't quite get all the way to "user-friendly" change tracking, but we can talk about how we may implement this later if necessary. For now, we can just say that the user created/updated the record for most of these.

One place I can think of where we could do something a little nicer is with anything that uses a Job to execute (via [ActiveJob](http://edgeguides.rubyonrails.org/active_job_basics.html)). For those, we can record the class name of the job performed and the parameters used to create it. This should tell us what was done and by whom in a more insightful way.

**Comment by rjosefsberg** [comment]
Once the chart of accounts gets underway Ill have a better idea about how to do this. But, on an abstract level, using the after_commit callback to create an even entry seems to be the right way to go.

**Comment by gav5** [comment]
@rjosefsberg paper_trail automatically records changes once you add `has_paper_trail` to the model class, so that shouldn't be necessary for this. The only thing that should need to be done is the formatting of these changes so they can be human-readable.

**Comment by gav5** [comment]
This should display the time at which the change was performed, the user who performed the change, and what was changed (in the case of an update).
