### ISSUE TITLE
Journal Entries

### ISSUE THREAD

**Issue by rjosefsberg** [jmennick/cornDog#41]
Hello gents,

In the current build I can't seem to create journal entries. I've done all the updating and restarted, but to no avail.  

Edit: Specifically, the modal opens and everything is where it should be, but hitting "save" doesn't close the modal and create the entry.

**Comment by gav5** [comment]
I cannot replicate what you are talking about.

What are you entering into the modal? Is the "Save" button disabled when you are trying to do this?

What browser are you using?
(I recommend trying on Chrome if you're using something else)

What commands are you entering to run the client?
(should just be `npm run dev`, no actual building)

**Comment by rjosefsberg** [comment]
When I use the word build I'm referring to the version that I pulled down. Habit from elsewhere. I pulled down masters and used npm run dev like usual.

Date: 4/30/17
Debit Cash 1
Credit AR 1
No Documents

I am running in Firefox. As a side node, the the calender and "MM/DD/YY" text aren't showing either in the date entry field. Havent tried it in other browsers yet. I'll re-confirm when I get home.

**Comment by gav5** [comment]
There's nothing wrong with what you are entering. I made [this record](http://localhost:3000/journals/138) with the same data just fine.

**Comment by gav5** [comment]
When you get a chance, see if anything is being printed to the console that might explain what's going on.

**Comment by rjosefsberg** [comment]
Unfortunately, I won't be able to check again until around 5 due to work stuff. I'll check it as soon as I get home.

**Comment by rjosefsberg** [comment]
Ok, its working in both Chrome and Firefox now. Weird. Closing this.
